# conda environment description file for the analysis-becca environment
#
# Create a conda environment in which to run Jupyter Notebooks in this directory with:
#
#   $ conda env create -f environment.yaml
#   $ conda activate Ariane
#
# To add new packages to the environment,
# add them to the dependencies list below,
# then update the activated environment with:
#
#   (Ariane)$ conda env update -f environment.yaml

name: Ariane

channels:
  - conda-forge
  - defaults

dependencies:
  - arrow
  - bottleneck
  - cmocean
  - dask
  - python-dateutil
  - jupyterlab
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - pip
  - python=3
  - pytz
  - scipy
  - xarray=0.16.2
  - ffmpeg
  - IPython
  - cartopy
  - scikit-learn=0.24.1

# pip install --user --editable /ocean/rbeutel/MEOPAR/tools/SalishSeaTools
